language: node_js
node_js:
  - "6"

branches:
  only:
    - master

before_script:
  - npm install -g elm
  - npm install -g create-elm-app
  - npm install glob -g
  - npm install -g firebase-tools

script:
  - elm-app build

after_success:
  - firebase deploy --only hosting --project fint-consumer-client-elm  --token=${FIREBASE_API_TOKEN}
